# Generated by Django 5.2.8 on 2025-11-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
