# Generated by Django 5.2.8 on 2025-11-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intend_id',
            new_name='stripe_payment_intent_id',
        ),
    ]
